name = "DataIngestion"
uuid = "83dcfd31-4fc0-4194-8ee5-c3b52bd3c2ac"
authors = ["Limen Research", "Mattia G. Bergomi", "Dario Sarra", "Pietro Vertechi"]
version = "1.0.0-DEV"

[deps]
ConcurrentUtilities = "f0e56b4a-5159-44fe-b623-3e5288b988bb"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"

[compat]
ConcurrentUtilities = "2"
DuckDB = "1.1"
IntervalSets = "0.7"
IterTools = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
