name = "DataIngestion"
uuid = "83dcfd31-4fc0-4194-8ee5-c3b52bd3c2ac"
authors = ["Limen Research", "Mattia G. Bergomi", "Dario Sarra", "Pietro Vertechi"]
version = "1.0.0-DEV"

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DuckDBUtils = "7d8cfb0f-d1ec-4adb-bc0e-59660d99800f"
FunSQL = "cf6cc811-59f4-4a10-b258-a8547a8f6407"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[sources]
DuckDBUtils = {path = "../DuckDBUtils"}

[compat]
DBInterface = "2.6.1"
FunSQL = "0.14.3, 0.15"
IntervalSets = "0.7.10"
IterTools = "1"
Tables = "1"
julia = "1.11"
