name = "DataIngestion"
uuid = "83dcfd31-4fc0-4194-8ee5-c3b52bd3c2ac"
authors = ["Limen Research", "Mattia G. Bergomi", "Dario Sarra", "Pietro Vertechi"]
version = "1.0.0-DEV"

[deps]
ConcurrentUtilities = "f0e56b4a-5159-44fe-b623-3e5288b988bb"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"

[compat]
ConcurrentUtilities = "2"
DuckDB = "1.1"
Glob = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
