name = "DuckDBUtils"
uuid = "7d8cfb0f-d1ec-4adb-bc0e-59660d99800f"
authors = ["Limen Research", "Mattia G. Bergomi", "Dario Sarra", "Pietro Vertechi"]
version = "1.0.0-DEV"

[deps]
ConcurrentUtilities = "f0e56b4a-5159-44fe-b623-3e5288b988bb"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
FunSQL = "cf6cc811-59f4-4a10-b258-a8547a8f6407"

[compat]
ConcurrentUtilities = "2"
DuckDB = "1.1"
FunSQL = "0.14.3"
julia = "1.11"
