seed = 5678
device = "cpu"
batchsize = 32
iterations = { "-v" = "iterations" }
shuffle = false

[optimizer]
name = "Adam"
eta = 1e-2

[[widgets]]
key = "iterations"
widget = "input"
label = "Iterations"
placeholder = "Select number of iterations"
type = "number"
min = 1
step = 1
value = 10
