name = "Pipelines"
uuid = "12f58945-0960-453a-85e3-e4614e9748b9"
authors = ["Limen Research", "Mattia G. Bergomi", "Pietro Vertechi"]
version = "1.0.0-DEV"

[deps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
