key = "cluster"
label = "Cluster"
needs_targets = false
needs_order = false
allows_weights = true
allows_partition = true

widgets = {}

[[methods.kmeans.widgets]]
key = "classes"
widget = "input"
label = "Classes"
placeholder = "Select number of classes"
type = "number"
min = 1
step = 1

[[methods.kmeans.widgets]]
key = "iterations"
widget = "input"
label = "Iterations"
placeholder = "Select number of iterations"
type = "number"
min = 1
step = 1
value = 100
required = false

[[methods.kmeans.widgets]]
key = "tol"
widget = "input"
label = "Tolerance"
placeholder = "Select tolerance"
type = "number"
min = 1e-6
step = 1e-6
value = 1e-6
required = false

# TODO: add other options
[[methods.dbscan.widgets]]
key = "radius"
widget = "input"
label = "Radius"
placeholder = "Select radius"
type = "number"
