key = "dimensionality_reduction"
label = "Dimensionality Reduction"
needs_targets = false
needs_order = false
allows_weights = false
allows_partition = true

[widgets.n_components]
widget = "input"
label = "Number of components"
placeholder = "Select number of components..."
type = "number"

methods.pca.widgets = []

[[methods.ppca.widgets]]
key = "iterations"
widget = "input"
label = "Iterations"
placeholder = "Select number of iterations"
type = "number"
min = 1
step = 1
value = 100
required = false

[[methods.ppca.widgets]]
key = "tol"
widget = "input"
label = "Tolerance"
placeholder = "Select tolerance"
type = "number"
min = 1e-6
step = 1e-6
value = 1e-6
required = false

[[methods.factoranalysis.widgets]]
key = "iterations"
widget = "input"
label = "Iterations"
placeholder = "Select number of iterations"
type = "number"
min = 1
step = 1
value = 100
required = false

[[methods.factoranalysis.widgets]]
key = "tol"
widget = "input"
label = "Tolerance"
placeholder = "Select tolerance"
type = "number"
min = 1e-6
step = 1e-6
value = 1e-6
required = false

methods.mds.widgets = []
