key = "glm"
label = "GLM"
needs_targets = true
needs_order = false
allows_weights = true
allows_partition = true

[widget_configs.distribution]
widget = "select"
label = "Noise"
placeholder = "Select noise model..."

[widget_configs.link]
widget = "select"
label = "Link"
placeholder = "Select link function..."
