key = "interp"
label = "Interpolation"
needs_targets = true
needs_order = false
allows_weights = false
allows_partition = true

[widgets.extrapolation_left]
widget = "select"
label = "Extrapolation (left)"
placeholder = "Select extrapolation function..."

[widgets.extrapolation_right]
widget = "select"
label = "Extrapolation (right)"
placeholder = "Select extrapolation function..."

[widgets.dir]
widget = "select"
label = "Extrapolation direction"
placeholder = "Select extrapolation direction..."
