key = "rescale"
label = "Rescale"
needs_targets = false
needs_order = false
allows_weights = false
allows_partition = true

[widget_types.target_suffix]
widget = "input"
label = "Target suffix"
placeholder = "Select target suffix..."
