key = "split"
label = "Split"
needs_targets = false
needs_order = true
allows_weights = false
allows_partition = false

[widget_types.tiles]
widget = "select"
label = "Tiles"
placeholder = "Select tiles..."
multiple = true
type = "number"
options = [1, 2]

[widget_types.percentile]
widget = "input"
label = "Percentile"
placeholder = "Select percentile..."
type = "number"
