key = "split"
label = "Split"
needs_targets = false
needs_order = true
allows_weights = false
allows_partition = false

[widget_configs.tiles]
widget = "select"
label = "Tiles"
placeholder = "Select tiles..."
multiple = true
type = "number"
options = [1, 2]

[widget_configs.percentile]
widget = "input"
label = "Percentile"
placeholder = "Select percentile..."
type = "number"
min = 0
max = 1
step = 0.01

[[methods.tiles.widgets]]
key = "tiles"

[[methods.percentile.widgets]]
key = "percentile"
