key = "split"
label = "Split"
needs_targets = false
needs_order = true
allows_weights = false
allows_partition = false

widget_configs = {}

[[methods.tiles.widgets]]
key = "tiles"
widget = "select"
label = "Tiles"
placeholder = "Select tiles..."
multiple = true
type = "number"
options = [1, 2]

[[methods.percentile.widgets]]
key = "percentile"
widget = "input"
label = "Percentile"
placeholder = "Select percentile..."
type = "number"
