[n_modes]
widget = "input"
label = "Number of modes"
placeholder = "Select number of modes..."
type = "number"

[max]
widget = "input"
label = "Maximum value"
placeholder = "Select maximum value of column..."
type = "number"

[lambda]
widget = "input"
label = "Scaling coefficient"
placeholder = "Rescale Gaussian curves horizontally by a given factor..."
type = "number"