[tiles]
widget = "select"
label = "Tiles"
placeholder = "Select tiles..."
multiple = true
type = "number"
options = [1, 2]

[percentile]
widget = "input"
label = "Percentile"
placeholder = "Select percentile..."
type = "number"
