key = "streamliner"
label = "Streamliner"
needs_targets = true
needs_order = true
allows_weights = false
allows_partition = true

[widgets.model]
widget = "select"
label = "Model configuration"
placeholder = "Select a model configuration..."

[widgets.training]
widget = "select"
label = "Training configuration"
placeholder = "Select a training configuration..."
