[suffix]
widget = "input"
label = "Suffix"
placeholder = "Select suffix..."

[output]
widget = "input"
label = "Output"
placeholder = "Select output name..."

[method]
widget = "select"
label = "Method"
placeholder = "Select method..."

[target]
widget = "select"
label = "Target"
placeholder = "Select target variable..."
options = { "-v" = "names" }

[targets]
widget = "select"
label = "Targets"
placeholder = "Select target variables..."
multiple = true
options = { "-v" = "names" }

[input]
widget = "select"
label = "Input"
placeholder = "Select input variable..."
options = { "-v" = "names" }

[inputs]
widget = "select"
label = "Inputs"
placeholder = "Select input variables..."
multiple = true
options = { "-v" = "names" }

[weights]
widget = "select"
label = "Weights"
placeholder = "Select weight variable..."
options = { "-v" = "names" }

[partition]
widget = "select"
label = "Partition"
placeholder = "Select partition variable..."
options = { "-v" = "names" }

[by]
widget = "select"
label = "Group"
placeholder = "Select grouping variables..."
multiple = true
options = { "-v" = "names" }

[order_by]
widget = "select"
label = "Order"
placeholder = "Select ordering variables..."
multiple = true
options = { "-v" = "names" }
