name: CI
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '/dashiboard/'
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.11'
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Develop and test Dashiboard
        shell: julia --project {0}
        run: |
          using Pkg: Pkg
          Pkg.add(Pkg.PackageSpec(name="DuckDB", rev="main"))
          Pkg.test("DataIngestion")
          Pkg.test("Pipelines")
          Pkg.test("DashiBoard")
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4 # TODO: code coverage for sub-packages?
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info